language: python

matrix:
  fast_finish: true
  include:
    - os: linux
      sudo: required
      python: 2.7
    - os: linux
      sudo: required
      python: 3.5
    - os: linux
      sudo: required
      python: 3.6
    - os: linux
      sudo: required
      python: 3.7
    - os: linux
      sudo: required
      python: 3.8
    - os: linux
      sudo: required
      python: pypy
    - os: linux
      sudo: required
      python: pypy3
    - os: osx
      language: generic
      env: PYVER=3
    - os: osx
      language: generic
      env: PYVER=2
  allow_failures:
    - os: linux
      sudo: required
      python: pypy
    - os: linux
      sudo: required
      python: pypy3
    - os: osx
      language: generic
      env: PYVER=3
    - os: osx
      language: generic
      env: PYVER=2

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libsdl2-2.0-0 libsdl2-ttf-2.0-0 libsdl2-mixer-2.0-0 libsdl2-image-2.0-0 libsdl2-gfx-2.0-0; fi
  - pip install -U pip
  - pip install git+https://github.com/a-hurst/pysdl2-dll.git
  - export PYSDL2_DLL_PATH=$(python -c "import sdl2dll; print(sdl2dll.get_dllpath())")
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sh .ci/install-osx-deps.sh; fi

install:
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sh .ci/venv-osx.sh; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source pysdl2-venv/bin/activate; fi
  - pip install -U numpy
  - pip install -U pytest
  - pip install .

env:
  global:
  - SDL_VIDEODRIVER=dummy
  - SDL_AUDIODRIVER=dummy
  - SDL_RENDER_DRIVER=software

script:
  - python -B -m pytest -v
