language: python

matrix:
 include:
    - name: "Python 3.7 on macOS w/ latest SDL2"
      os: osx
      language: shell
      env: PYSDL2_DLL_VERSION=2.0.10
      before_install: brew install python && brew link python
    - name: "Python 2.7 on macOS w/ latest SDL2"
      os: osx
      language: shell
      env: PYSDL2_DLL_VERSION=2.0.10
      before_install: brew install python@2 && brew link python@2
    - name: "Python 3.7 on macOS w/ SDL2 2.0.8"
      os: osx
      language: shell
      env: PYSDL2_DLL_VERSION=2.0.8
      before_install: brew install python && brew link python
    - name: "Python 3.7 on macOS w/ SDL2 2.0.6"
      os: osx
      language: shell
      env: PYSDL2_DLL_VERSION=2.0.6
      before_install: brew install python && brew link python
#  allow_failures:
#    - os: linux
#      sudo: required
#      python: pypy
#    - os: linux
#      sudo: required
#      python: pypy3
#    - os: osx
#      language: shell
#      env: PYVER=3
#    - os: osx
#      language: shell
#      env: PYVER=2

#before_install:
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libsdl2-2.0-0 libsdl2-ttf-2.0-0 libsdl2-mixer-2.0-0 libsdl2-image-2.0-0 libsdl2-gfx-1.0-0; fi
#  - pip install git+https://github.com/a-hurst/pysdl2-dll.git
#  - export PYSDL2_DLL_PATH=$(python -c "import sdl2dll; print(sdl2dll.get_dllpath())")

install:
  - python -m pip install --upgrade pip
  - python .ci/getsdl2.py
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PYSDL2_DLL_PATH=$(pwd)/dlls; fi 
  - python -m pip install --upgrade numpy pytest
  - python -m pip install .

#script:
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sh .ci/venv-osx.sh; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source pysdl2-venv/bin/activate; fi
#  - python -m cibuildwheel --output-dir wheelhouse

env:
  global:
  - SDL_VIDEODRIVER=dummy
  - SDL_AUDIODRIVER=dummy
  - SDL_RENDER_DRIVER=software
  #- CIBW_TEST_REQUIRES='numpy pytest'
  #- CIBW_TEST_COMMAND='pytest -v'
  #- CIBW_MANYLINUX_X86_64_IMAGE=manylinux2014
  #- CIBW_MANYLINUX_I686_IMAGE=manylinux2014
  #- CIBW_BEFORE_BUILD_LINUX='chmod +x ./.ci/install-linux-deps.sh && /bin/bash ./.ci/install-linux-deps.sh'

script:
  - python -B -m pytest -vvl
