environment:
  SDL_VIDEODRIVER: dummy
  SDL_AUDIODRIVER: dummy
  SDL_RENDER_DRIVER: software
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python38"
    - PYTHON: "C:\\Python38-x64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "pip install -U pip"
  - "pip install git+https://github.com/a-hurst/pysdl2-dll.git"
  - "python -c 'import sdl2dll; print(sdl2dll.get_dllpath())' > dllpath.txt"
  - "set /p PYSDL2_DLL_PATH=<dllpath.txt"
  - "pip install -U numpy pytest"
  - "pip install ."

build: off

test_script:
  - "python -B -m pytest -v"
